version: '3'

services:
  web:
    container_name: coding-drills
    build:
      dockerfile: ./dockerfiles/web.dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
  run-code-server:
    container_name: run-code-server
    build:
      dockerfile: dockerfiles/docker-python-fastapi.dockerfile
      context: .
    privileged: true
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    working_dir: /docker-python-fastapi
    volumes:
      - ./docker-python-fastapi:/docker-python-fastapi
    command: sh -c "dockerd-entrypoint.sh & uvicorn main:app --host 0.0.0.0 --port 8000"
#    command: sh -c "dockerd-entrypoint.sh & uvicorn main:app --reload --host 0.0.0.0 --port 8000"
